"""Initial migration

Revision ID: dd98cd7c7f29
Revises: b32dcf02fd8b
Create Date: 2026-03-21 14:50:25.003781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd98cd7c7f29'
down_revision = 'b32dcf02fd8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('control')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('control', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
